name: Testing the Action

on: [pull_request]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - uses: artis3n/signoff-new-commit@HEAD
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
